"""Jeu d'essai des tests : un projet fictif de robot, 60 composants répartis en 9 blocs.

Il sert aux tests qui ont besoin d'une base déjà remplie ; il n'est jamais chargé par
l'application. Les prix sont ceux de pièces du commerce ; le total estimé vaut 3184,98 € HT
pour un budget de 3000 €, ce qui exerce la règle d'arrondi (arrondir chaque PU HT avant de
multiplier donnerait 3184,96 €).
"""

import sqlite3
from typing import Any

from backend import db

HORODATAGE = "2026-01-15T10:00:00"

PARAMETRES: dict[str, str] = {
    "nom_projet": "Projet d'essai",
    "prefixe_id": "ESSAI",
    "budget_ht": "3000",
    "taux_tva_defaut": "0.2",
}

# Vocabulaire propre au projet fictif, ajouté aux listes génériques
# (liste, code, libellé, sens pour les types de mouvement).
LISTES: tuple[tuple[str, str, str, str | None], ...] = (
    ("mode_appro", "Stock interne", "Stock interne", None),
    ("mode_appro", "Fourni atelier", "Fourni par l'atelier", None),
    ("mode_appro", "Fourni partenaire", "Fourni par le partenaire", None),
    ("mode_appro", "Fabrication atelier", "Fabrication atelier", None),
    ("statut_appro", "Stock atelier", "Stock atelier", None),
    ("type_mouvement", "Pret", "Prêt", "Entree"),
    ("type_mouvement", "Retour pret", "Retour de prêt", "Sortie"),
)

BLOCS: tuple[dict[str, Any], ...] = (
    {
        "code": "TR",
        "nom": "Transverse",
        "ordre": 1,
        "description": "Composants communs à plusieurs nœuds",
    },
    {
        "code": "IHM",
        "nom": "IHM",
        "ordre": 2,
        "description": "Interface homme-machine : poste opérateur, écran, pupitre",
    },
    {
        "code": "ODB",
        "nom": "Ordinateur de bord",
        "ordre": 3,
        "description": "Calculateur central, stockage, réseau embarqué",
    },
    {
        "code": "AGI",
        "nom": "Actionnement",
        "ordre": 4,
        "description": "Moteurs, réducteurs, drivers et codeurs des axes",
    },
    {
        "code": "OBS",
        "nom": "Perception",
        "ordre": 5,
        "description": "Caméras, capteurs de distance et d'environnement",
    },
    {
        "code": "ALI",
        "nom": "Alimentation",
        "ordre": 6,
        "description": "Production, conversion, protection et distribution d'énergie",
    },
    {
        "code": "BMP",
        "nom": "Pare-chocs",
        "ordre": 7,
        "description": "Mécanisme de pare-chocs : translation et rotation",
    },
    {
        "code": "BUS",
        "nom": "Bus et connectique",
        "ordre": 8,
        "description": "Bus CAN, faisceaux, connecteurs, étanchéité",
    },
    {
        "code": "MEC",
        "nom": "Mécanique et matière",
        "ordre": 9,
        "description": "Roulements, profilés, boîtiers",
    },
)

FOURNISSEURS: tuple[dict[str, Any], ...] = (
    {
        "nom": "Mouser",
        "type": "Distributeur pro",
        "base_prix_defaut": "HT",
        "pays": "France",
        "site_web": "https://www.mouser.fr",
    },
    {
        "nom": "Digikey",
        "type": "Distributeur pro",
        "base_prix_defaut": "HT",
        "pays": "France",
        "site_web": "https://www.digikey.fr",
    },
    {
        "nom": "Farnell",
        "type": "Distributeur pro",
        "base_prix_defaut": "HT",
        "pays": "France",
        "site_web": "https://fr.farnell.com",
    },
    {
        "nom": "RS Components",
        "type": "Distributeur pro",
        "base_prix_defaut": "HT",
        "pays": "France",
        "site_web": "https://fr.rs-online.com",
    },
    {
        "nom": "TME",
        "type": "Distributeur pro",
        "base_prix_defaut": "HT",
        "pays": "Pologne",
        "site_web": "https://www.tme.eu/fr",
    },
    {
        "nom": "Kubii",
        "type": "Grand public",
        "base_prix_defaut": "TTC",
        "pays": "France",
        "site_web": "https://www.kubii.com",
    },
    {
        "nom": "Gotronic",
        "type": "Grand public",
        "base_prix_defaut": "TTC",
        "pays": "France",
        "site_web": "https://www.gotronic.fr",
    },
    {
        "nom": "Conrad",
        "type": "Grand public",
        "base_prix_defaut": "TTC",
        "pays": "France",
        "site_web": "https://www.conrad.fr",
    },
    {
        "nom": "LDLC",
        "type": "Grand public",
        "base_prix_defaut": "TTC",
        "pays": "France",
        "site_web": "https://www.ldlc.com",
    },
    {
        "nom": "Amazon / StepperOnline",
        "type": "Grand public",
        "base_prix_defaut": "TTC",
        "pays": "A verifier",
        "site_web": "https://www.omc-stepperonline.com/fr",
    },
    {
        "nom": "Parts and Go",
        "type": "Grand public",
        "base_prix_defaut": "TTC",
        "pays": "France",
        "site_web": "https://www.partsandgo.fr",
    },
    {
        "nom": "steppermotor.fr",
        "type": "Grand public",
        "base_prix_defaut": "TTC",
        "pays": "France",
        "site_web": "https://www.steppermotor.fr",
    },
    {
        "nom": "DZ Alu Pro",
        "type": "Distributeur pro",
        "base_prix_defaut": "HT",
        "pays": "France",
        "site_web": "https://dzalu-pro.fr",
    },
    {
        "nom": "Atelier",
        "type": "Interne",
        "base_prix_defaut": "HT",
        "pays": "France",
        "site_web": None,
    },
    {
        "nom": "Partenaire",
        "type": "Interne",
        "base_prix_defaut": "HT",
        "pays": "France",
        "site_web": None,
    },
    {
        "nom": "Magasin",
        "type": "Interne",
        "base_prix_defaut": "HT",
        "pays": "France",
        "site_web": None,
    },
)

COMPOSANTS: tuple[dict[str, Any], ...] = (
    {
        "id": "ESSAI-AGI-001",
        "bloc_code": "AGI",
        "fonction": "Motorisation axes L1/L2/L3",
        "designation": "Kit closed-loop Nema 34 : moteur 8,2 Nm 6 A + driver CL86T + codeur 1000 "
        "ppr",
        "ref_fabricant": "34HE45-6004S + CL86T",
        "fabricant": "StepperOnline",
        "mode_appro": "Achat",
        "fournisseur_nom": "Amazon / StepperOnline",
        "lien_produit": "https://www.omc-stepperonline.com/fr/e-serie-nema-34-moteur-pas-a-pas-bipolar-1-8deg-8-2-nm-1161-45oz-in-6-0a-86x86x114mm-4-fils-34he45-6004s",
        "qte_besoin": 3,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 178.0,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "D2",
    },
    {
        "id": "ESSAI-AGI-002",
        "bloc_code": "AGI",
        "fonction": "Reduction axes L2/L3",
        "designation": "Reducteur planetaire Nema 34 serie 86PX",
        "ref_fabricant": "86PX",
        "mode_appro": "Achat",
        "fournisseur_nom": "steppermotor.fr",
        "lien_produit": "https://www.steppermotor.fr/goods-1648-R%C3%A9ducteur-plan%C3%A9taire-Nema-34-86PX-s%C3%A9rie-rapport-5-1-%C3%A0-100-1-pour-moteur-pas-%C3%A0-pas-de-86-mm.html",
        "qte_besoin": 3,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 48.78,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "D2",
    },
    {
        "id": "ESSAI-AGI-003",
        "bloc_code": "AGI",
        "fonction": "Mesure de position en bout de cinematique",
        "designation": "Codeur magnetique AS5047D-ATSM",
        "ref_fabricant": "AS5047D-ATSM",
        "fabricant": "ams-OSRAM",
        "mode_appro": "Achat",
        "fournisseur_nom": "Mouser",
        "lien_produit": "https://www.mouser.fr/ProductDetail/ams-OSRAM/AS5047D-ATSM",
        "qte_besoin": 3,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "D2",
    },
    {
        "id": "ESSAI-AGI-004",
        "bloc_code": "AGI",
        "fonction": "Mesure de position (verin)",
        "designation": "Codeur a cable MRA-G055-101D4",
        "ref_fabricant": "MRA-G055-101D4",
        "mode_appro": "Achat",
        "fournisseur_nom": "RS Components",
        "lien_produit": "https://fr.rs-online.com/web/p/codeurs/2858882",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 236.64,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
    },
    {
        "id": "ESSAI-ALI-001",
        "bloc_code": "ALI",
        "fonction": "Alimentation secteur principale",
        "designation": "Alimentation AC/DC 48 V",
        "ref_fabricant": "LRS-1200-48 ou RSP-320-48",
        "fabricant": "MEAN WELL",
        "mode_appro": "Achat",
        "fournisseur_nom": "Farnell",
        "lien_produit": "https://fr.farnell.com/mean-well/lrs-1200-48/alimentation-ac-dc-48v-25a-1-2kw/dp/4723219",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 150.0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
        "origine_exigence": "D3",
    },
    {
        "id": "ESSAI-ALI-002",
        "bloc_code": "ALI",
        "fonction": "Distribution de puissance",
        "designation": "Carte de puissance custom",
        "mode_appro": "Fabrication atelier",
        "fournisseur_nom": "Atelier",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-003",
        "bloc_code": "ALI",
        "fonction": "Conversion 48 -> 5 V",
        "designation": "Convertisseur DC-DC DDR-60L-5",
        "ref_fabricant": "DDR-60L-5",
        "fabricant": "MEAN WELL",
        "mode_appro": "Achat",
        "fournisseur_nom": "Farnell",
        "lien_produit": "https://fr.farnell.com/mean-well/ddr-60l-5/convertisseur-dc-dc-5v-10-8a/dp/3003010",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 34.0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-004",
        "bloc_code": "ALI",
        "fonction": "Conversion 48 -> 12 V",
        "designation": "Convertisseur DC-DC 12 V",
        "ref_fabricant": "A DEFINIR",
        "fabricant": "MEAN WELL",
        "mode_appro": "Achat",
        "fournisseur_nom": "Farnell",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 34.0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-005",
        "bloc_code": "ALI",
        "fonction": "Conversion 48 -> 24 V",
        "designation": "Convertisseur DC-DC 24 V",
        "ref_fabricant": "A DEFINIR",
        "fabricant": "MEAN WELL",
        "mode_appro": "Achat",
        "fournisseur_nom": "Farnell",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 34.0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-006",
        "bloc_code": "ALI",
        "fonction": "Bascule secteur / batterie",
        "designation": "ATS ERDN40-48",
        "ref_fabricant": "ERDN40-48",
        "fabricant": "MEAN WELL",
        "mode_appro": "Achat",
        "fournisseur_nom": "Mouser",
        "lien_produit": "https://eu.mouser.com/ProductDetail/MEAN-WELL/ERDN40-48",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 30.7,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "D4",
    },
    {
        "id": "ESSAI-ALI-007",
        "bloc_code": "ALI",
        "fonction": "Gestion batterie",
        "designation": "BMS 48 V",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "D4",
    },
    {
        "id": "ESSAI-ALI-008",
        "bloc_code": "ALI",
        "fonction": "Source d'energie autonome",
        "designation": "Pack batterie 48 V",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "D4",
    },
    {
        "id": "ESSAI-ALI-009",
        "bloc_code": "ALI",
        "fonction": "Commutation puissance 48 V",
        "designation": "Relais statique CMX60D20",
        "ref_fabricant": "CMX60D20",
        "fabricant": "Sensata Crydom",
        "mode_appro": "Achat",
        "fournisseur_nom": "Digikey",
        "lien_produit": "https://www.digikey.fr/fr/products/detail/sensata-crydom/CMX60D20/1771455",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 89.4,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-010",
        "bloc_code": "ALI",
        "fonction": "Commutation 5 / 12 / 24 V",
        "designation": "Relais G5LE-1 DC24",
        "ref_fabricant": "G5LE-1-DC24",
        "fabricant": "Omron",
        "mode_appro": "Achat",
        "fournisseur_nom": "Digikey",
        "lien_produit": "https://www.digikey.fr/fr/products/detail/omron-electronics-inc-emc-div/G5LE-1-DC24/280367",
        "qte_besoin": 3,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 1.72,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-011",
        "bloc_code": "ALI",
        "fonction": "Mesure de puissance 5 / 12 / 24 V",
        "designation": "Module INA260",
        "ref_fabricant": "INA260 / 4226",
        "fabricant": "Adafruit / TI",
        "mode_appro": "Achat",
        "fournisseur_nom": "Digikey",
        "lien_produit": "https://www.digikey.fr/fr/products/detail/adafruit-industries-llc/4226/10130492",
        "qte_besoin": 3,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 8.69,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-012",
        "bloc_code": "ALI",
        "fonction": "Mesure de puissance 48 V",
        "designation": "Circuit INA238AIDGSR",
        "ref_fabricant": "INA238AIDGSR",
        "fabricant": "Texas Instruments",
        "mode_appro": "Achat",
        "fournisseur_nom": "Digikey",
        "lien_produit": "https://www.digikey.fr/fr/products/detail/texas-instruments/INA238AIDGSR/15857213",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 2.85,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-013",
        "bloc_code": "ALI",
        "fonction": "Commande relais",
        "designation": "Transistor 2N2222A",
        "ref_fabricant": "2N2222A",
        "fabricant": "Diotec",
        "mode_appro": "Achat",
        "fournisseur_nom": "Farnell",
        "lien_produit": "https://fr.farnell.com/diotec/2n2222a/transistor-npn-40v-0-6a-to-92/dp/4555427",
        "qte_besoin": 4,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 0.8,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-014",
        "bloc_code": "ALI",
        "fonction": "Chaine AU - coupure puissance",
        "designation": "Interrupteur d'arret d'urgence 48 V / 125 A",
        "ref_fabricant": "ED125-1",
        "mode_appro": "Achat",
        "fournisseur_nom": "Parts and Go",
        "lien_produit": "https://www.partsandgo.fr/fr/arrets-d-urgence/52432-arret-d-urgence-125a-48vmaxi-unipolaire-ed125-1.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 34.0,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "D6",
    },
    {
        "id": "ESSAI-ALI-015",
        "bloc_code": "ALI",
        "fonction": "Chaine AU - relais de securite",
        "designation": "Relais / contacteur de securite",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "D6",
    },
    {
        "id": "ESSAI-ALI-016",
        "bloc_code": "ALI",
        "fonction": "Protection generale 230 V",
        "designation": "Disjoncteur modulaire 230 V 10 A courbe C",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-017",
        "bloc_code": "ALI",
        "fonction": "Protection par axe",
        "designation": "Disjoncteur magnetothermique moteur",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 3,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-018",
        "bloc_code": "ALI",
        "fonction": "Protection des lignes",
        "designation": "Fusibles + porte-fusibles",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ALI-019",
        "bloc_code": "ALI",
        "fonction": "Connectique forte puissance",
        "designation": "Connecteur XT60PW-M",
        "ref_fabricant": "XT60PW-M",
        "fabricant": "Amass",
        "mode_appro": "Achat",
        "fournisseur_nom": "TME",
        "lien_produit": "https://www.tme.eu/fr/details/xt60pw-m/connecteurs-dc/amass/",
        "qte_besoin": 4,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 1.34,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "D6",
    },
    {
        "id": "ESSAI-ALI-020",
        "bloc_code": "ALI",
        "fonction": "Connectique faible puissance",
        "designation": "Connecteur XT30PW-M",
        "ref_fabricant": "XT30PW-M",
        "fabricant": "Amass",
        "mode_appro": "Achat",
        "fournisseur_nom": "TME",
        "lien_produit": "https://www.tme.eu/fr/details/xt30pw-m/connecteurs-dc/amass/",
        "qte_besoin": 6,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 0.7,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-BMP-001",
        "bloc_code": "BMP",
        "fonction": "Translation bumper",
        "designation": "Motoreducteur DC 6 V 210 tr/min",
        "ref_fabricant": "FIT0521",
        "fabricant": "DFRobot",
        "mode_appro": "Achat",
        "fournisseur_nom": "Farnell",
        "lien_produit": "https://fr.farnell.com/dfrobot/fit0521",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 17.16,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-BMP-002",
        "bloc_code": "BMP",
        "fonction": "Rotation bumper",
        "designation": "Servomoteur 270 deg 7,2 V",
        "ref_fabricant": "SER0044",
        "fabricant": "DFRobot",
        "mode_appro": "Achat",
        "fournisseur_nom": "Farnell",
        "lien_produit": "https://fr.farnell.com/dfrobot/ser0044/servomoteur-270-310-1-7-2v/dp/3769950",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 13.71,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-BUS-001",
        "bloc_code": "BUS",
        "fonction": "Bus CAN",
        "designation": "Cable bus CAN blinde + resistances de terminaison 120 Ohm",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-BUS-002",
        "bloc_code": "BUS",
        "fonction": "Etancheite traversees",
        "designation": "Presse-etoupes + connecteurs IP67",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 2,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 20.0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "BESOIN 17",
    },
    {
        "id": "ESSAI-BUS-003",
        "bloc_code": "BUS",
        "fonction": "Filtrage / decouplage",
        "designation": "Condensateurs de decouplage",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-BUS-004",
        "bloc_code": "BUS",
        "fonction": "Cablage",
        "designation": "Faisceau puissance + signal",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-BUS-005",
        "bloc_code": "BUS",
        "fonction": "Connectique commande",
        "designation": "Connecteurs JST-XH + contacts + outil de sertissage",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-IHM-001",
        "bloc_code": "IHM",
        "fonction": "IHM distante (poste operateur)",
        "designation": "Logiciel de supervision sur PC partenaire",
        "mode_appro": "Fourni partenaire",
        "fournisseur_nom": "Partenaire",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-IHM-002",
        "bloc_code": "IHM",
        "fonction": "Ecran embarque",
        "designation": 'Dalle tactile 7" HDMI',
        "ref_fabricant": "Waveshare 7inch HDMI LCD (C)",
        "fabricant": "Waveshare",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/ecrans-supports/3789-ecran-lcd-tactile-capacitif-de-7-pouces-pour-raspberry-jetson-3272496312562.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 49.5,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "BESOIN 19",
    },
    {
        "id": "ESSAI-IHM-003",
        "bloc_code": "IHM",
        "fonction": "Pupitre de commande",
        "designation": "Boutons poussoirs + interrupteurs",
        "mode_appro": "Fourni atelier",
        "fournisseur_nom": "Atelier",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-IHM-004",
        "bloc_code": "IHM",
        "fonction": "Voyants d'etat",
        "designation": "Voyants lumineux / colonne LED",
        "mode_appro": "Fourni atelier",
        "fournisseur_nom": "Atelier",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-IHM-005",
        "bloc_code": "IHM",
        "fonction": "Chaine AU - organe de commande",
        "designation": "Bouton coup-de-poing",
        "mode_appro": "Achat",
        "fournisseur_nom": "Gotronic",
        "lien_produit": "https://www.gotronic.fr/art-bouton-arret-urgence-40369.htm",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 7.5,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "Securite",
    },
    {
        "id": "ESSAI-IHM-006",
        "bloc_code": "IHM",
        "fonction": "Commande operateur",
        "designation": "Joystick USB Speedlink Competition Pro",
        "ref_fabricant": "COM-09032",
        "fabricant": "Speedlink",
        "mode_appro": "Achat",
        "fournisseur_nom": "Conrad",
        "lien_produit": "https://www.conrad.fr/fr/p/speedlink-competition-pro-extra-joystick-usb-pc-android-noir-rouge-1893215.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 33.99,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-IHM-007",
        "bloc_code": "IHM",
        "fonction": "Retour video operateur",
        "designation": "Camera IP PoE U121-B-V11",
        "ref_fabricant": "U121-B-V11",
        "mode_appro": "Achat",
        "fournisseur_nom": "Gotronic",
        "lien_produit": "https://www.gotronic.fr/art-module-camera-poe--48471.htm",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 34.9,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-MEC-001",
        "bloc_code": "MEC",
        "fonction": "Guidage",
        "designation": "Roulement rigide a billes 61804 (20x32x7)",
        "ref_fabricant": "61804",
        "fabricant": "SKF",
        "mode_appro": "Achat",
        "qte_besoin": 2,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 16.87,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
    },
    {
        "id": "ESSAI-MEC-002",
        "bloc_code": "MEC",
        "fonction": "Guidage etanche",
        "designation": "Roulement inox etanche W 61801-2RS1 (12x21x5)",
        "ref_fabricant": "W 61801-2RS1",
        "fabricant": "SKF",
        "mode_appro": "Achat",
        "qte_besoin": 2,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 32.14,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
    },
    {
        "id": "ESSAI-MEC-003",
        "bloc_code": "MEC",
        "fonction": "Guidage bumper",
        "designation": "Roulement inox W 618/6 (6x13x3,5)",
        "ref_fabricant": "W 618/6",
        "fabricant": "SKF",
        "mode_appro": "Achat",
        "qte_besoin": 3,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 19.14,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
    },
    {
        "id": "ESSAI-MEC-004",
        "bloc_code": "MEC",
        "fonction": "Structure",
        "designation": "Tubes aluminium",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "fournisseur_nom": "DZ Alu Pro",
        "lien_produit": "https://dzalu-pro.fr/cat%C3%A9gories/profiles_standards/tubes_ronds/",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 500.0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
    },
    {
        "id": "ESSAI-MEC-005",
        "bloc_code": "MEC",
        "fonction": "Protection electronique",
        "designation": "Boitier de jonction IP67 polycarbonate",
        "ref_fabricant": "A DEFINIR",
        "mode_appro": "Achat",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 70.0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "BESOIN 17",
    },
    {
        "id": "ESSAI-OBS-001",
        "bloc_code": "OBS",
        "fonction": "Caracterisation surface / parallelisme",
        "designation": "Camera 3D RealSense D435i",
        "ref_fabricant": "D435i",
        "fabricant": "Intel RealSense",
        "mode_appro": "Achat",
        "fournisseur_nom": "Digikey",
        "lien_produit": "https://www.digikey.fr/fr/products/detail/realsense/999AFR/9926004",
        "qte_besoin": 2,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 303.92,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-OBS-002",
        "bloc_code": "OBS",
        "fonction": "Temperature / humidite",
        "designation": "Module BME280",
        "ref_fabricant": "BME280 / VMA335",
        "fabricant": "Bosch",
        "mode_appro": "Achat",
        "fournisseur_nom": "Gotronic",
        "lien_produit": "https://www.gotronic.fr/art-module-bme280-vma335-31197.htm",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 19.9,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "BESOIN 32",
    },
    {
        "id": "ESSAI-OBS-003",
        "bloc_code": "OBS",
        "fonction": "Mesure de distance",
        "designation": "Module ToF VL53L4CD",
        "ref_fabricant": "3692",
        "fabricant": "Adafruit / ST",
        "mode_appro": "Achat",
        "fournisseur_nom": "Gotronic",
        "lien_produit": "https://www.gotronic.fr/art-module-tof-120cm-46565.htm",
        "qte_besoin": 4,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 17.75,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-OBS-004",
        "bloc_code": "OBS",
        "fonction": "Interface capteurs (proto)",
        "designation": "Bornier de repartition",
        "mode_appro": "Fabrication atelier",
        "fournisseur_nom": "Atelier",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "Acte",
        "statut_appro": "Non lance",
        "origine_exigence": "D5",
    },
    {
        "id": "ESSAI-ODB-001",
        "bloc_code": "ODB",
        "fonction": "Calculateur central",
        "designation": "Raspberry Pi 5 8 Go",
        "ref_fabricant": "SC1112",
        "fabricant": "Raspberry Pi",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/cartes-nano-ordinateurs/4106-1832-raspberry-pi-5-5056561803326.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 204.0,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-002",
        "bloc_code": "ODB",
        "fonction": "Stockage systeme",
        "designation": "Carte microSD 64 Go classe 10",
        "fabricant": "SanDisk",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/support-de-stockage/2794-carte-micro-sd-sandisk-classe-10-3272496311411.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 18.0,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-003",
        "bloc_code": "ODB",
        "fonction": "Support SSD",
        "designation": "HAT M.2 pour Raspberry Pi 5",
        "fabricant": "Raspberry Pi",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/hat-dac-modules/4114-m2-hat-pour-raspberry-pi-5-5056561803463.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 14.1,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-004",
        "bloc_code": "ODB",
        "fonction": "Stockage base PostgreSQL",
        "designation": "SSD NVMe M.2 2280 128 Go",
        "fabricant": "MakerDisk",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/support-de-stockage/4260-1963-disque-dur-ssd-nvme-m2-2280-makerdisk-3272496317512.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 45.6,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-005",
        "bloc_code": "ODB",
        "fonction": "Interface CAN du RPi",
        "designation": "RS485 CAN HAT",
        "fabricant": "Waveshare",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/modules-relais/2487-rs485-can-hat-pour-raspberry-pi-kubii-3272496014381.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 11.95,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-006",
        "bloc_code": "ODB",
        "fonction": "Liaison IHM distante",
        "designation": "Cable Ethernet Cat6 10 m",
        "fabricant": "Vention",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/hub-cables-adaptateurs/4253-1960-cable-reseau-ethernet-cat6-gigabit-rj45-vention-3272496317505.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 7.8,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-007",
        "bloc_code": "ODB",
        "fonction": "Refroidissement",
        "designation": "Ventilateur / dissipateur RPi 5",
        "fabricant": "Raspberry Pi",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/ventilateurs-dissipateurs-thermiques/4109-ventilateur-dissipateur-pour-raspberry-pi-5-5056561803357.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 6.0,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-008",
        "bloc_code": "ODB",
        "fonction": "Alimentation RPi (option)",
        "designation": "Alimentation USB-C 27 W",
        "fabricant": "Raspberry Pi",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/alimentations/4107-1818-alimentation-raspberry-pi-27w-usb-c-5056561803401.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 12.9,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-009",
        "bloc_code": "ODB",
        "fonction": "Liaison ecran embarque",
        "designation": "Cable micro-HDMI vers HDMI 1 m",
        "fabricant": "Raspberry Pi",
        "mode_appro": "Achat",
        "fournisseur_nom": "Kubii",
        "lien_produit": "https://www.kubii.com/fr/cables-adaptateurs-video/2687-1759-cable-micro-hdmi-vers-hdmi-officiel-raspberry-pi-3272496315570.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 5.94,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-010",
        "bloc_code": "ODB",
        "fonction": "Reseau embarque",
        "designation": "Switch Ethernet 5 ports",
        "ref_fabricant": "GS-105B v5",
        "fabricant": "ZyXEL",
        "mode_appro": "Achat",
        "fournisseur_nom": "LDLC",
        "lien_produit": "https://www.ldlc.com/fiche/PB00666793.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 14.95,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-ODB-011",
        "bloc_code": "ODB",
        "fonction": "Alimentation camera IP",
        "designation": "Injecteur / adaptateur PoE",
        "mode_appro": "Achat",
        "fournisseur_nom": "LDLC",
        "lien_produit": "https://www.ldlc.com/fiche/PB00200389.html",
        "qte_besoin": 1,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 11.95,
        "base_prix_releve": "TTC",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-TR-001",
        "bloc_code": "TR",
        "fonction": "Transceiver CAN",
        "designation": "MCP2562 / MCP2562-E-P",
        "ref_fabricant": "MCP2562-E-P",
        "fabricant": "Microchip",
        "mode_appro": "Achat",
        "fournisseur_nom": "Mouser",
        "lien_produit": "https://www.mouser.fr/ProductDetail/Microchip-Technology/MCP2562-E-P",
        "qte_besoin": 4,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 1.13,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A sourcer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
    {
        "id": "ESSAI-TR-002",
        "bloc_code": "TR",
        "fonction": "Controleur de noeud",
        "designation": "ESP32-S3-DevKitC-1",
        "ref_fabricant": "ESP32-S3-DevKitC-1-N8R2",
        "fabricant": "Espressif",
        "mode_appro": "Achat",
        "fournisseur_nom": "Digikey",
        "lien_produit": "https://www.digikey.fr/fr/products/detail/espressif-systems/ESP32-S3-DEVKITC-1-N32R16V/26658348",
        "qte_besoin": 3,
        "qte_rechange": 0,
        "qte_disponible": 0,
        "pu_releve": 16.82,
        "base_prix_releve": "HT",
        "taux_tva": 0.2,
        "statut_choix": "A confirmer",
        "statut_appro": "Non lance",
        "origine_exigence": "APS",
    },
)


def charger_jeu_essai(conn: sqlite3.Connection) -> None:
    """Remplit une base migrée et vide avec le jeu d'essai."""
    with db.transaction(conn):
        for cle, valeur in PARAMETRES.items():
            db.insert_row(conn, "parametre", {"cle": cle, "valeur": valeur})
        for ordre, (liste, code, libelle, sens) in enumerate(LISTES, start=10):
            db.insert_row(
                conn,
                "valeur_liste",
                {"liste": liste, "code": code, "libelle": libelle, "ordre": ordre, "sens": sens},
            )
        for bloc in BLOCS:
            db.insert_row(conn, "bloc", bloc)
        for fournisseur in FOURNISSEURS:
            db.insert_row(conn, "fournisseur", fournisseur)
        for composant in COMPOSANTS:
            db.insert_row(
                conn, "composant", {**composant, "cree_le": HORODATAGE, "modifie_le": HORODATAGE}
            )
